name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: disable git crlf conversion
      run: git config --global core.autocrlf false
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v3
    - name: disable git crlf conversion
      run: git config --global core.autocrlf false
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: disable git crlf conversion
      run: git config --global core.autocrlf false
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Test
      run: cargo test --verbose
